### ISSUE TITLE
Structure, templates and some problem

### ISSUE THREAD

**Issue by westprophet** [faebeee/react-component-creator-plugin#7]
Component file structure and file templates

I liked your idea of developing this plugin.

I would like to be able to configure the custom structure of the component folder.

For example, to indicate the path to the templates folder, your script reads each file and generates it according to the template you specified. If you know what I mean.

There is also a problem when creating your own template for the file an empty folder is created.

**Comment by faebeee** [comment]
Hi @westprophet I've fixed the bug regarding the empty folder structure. This was related to https://github.com/component-creator-plugin/react-component-creator-plugin/issues/8 

Regarding your feature request I'll evaluate that und see what is possible and how. If you have any experience with java, I'm open for any PR since my knowledge about this, is quite small
